spring:
  datasource:
    # Database configuration (will be overridden by Docker environment variables if ran with docker-compose)
    url: jdbc:mysql://localhost:3306/english_now?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    # database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
